dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh | bash
notifications:
        slack:
                rooms:
                        secure:
cTvVjSiiJ9c0jOxkxwH7cu6Zu4t/FWt3nLveT+yYsVp7vRXF8SXXBgL1b9AuACiPRG3jSj+n/zewluRJc9W5sknwcgnKJf8mYuidZtap/c32NmFwaHiVY4SiaCsLpt+t/Wfih6B/D7YEu/BfSLaqaOBdRjMbu3kf+uJr39lzIc5eVCwwsxJLQtMHyf1mfdYw9qXMr9ZwX1Bk/EV4fPLpUlMo4wou5vzvM1CxUjB8+VwpB0454DnXiEceC+54jxc4m7am+itWbCBOLtfzUnvhnYWSmt4S5s5fQlWjtITdENL7/SWBsP3jC5MAcKaOekbDsu9wfBzqlvYXBXsZaI9jCQCXrg+Jk1xYEjdoTj0QlxF11+oL8Q4zEHT2P8eujCJCJ8veJqm90awpqv0ouggtwU1b8NxXes56moQBkzLFdpgY17CvTMIYYMKP/8YTa1L3hErzQKbcXAf0JmirZnaA4rdoRGaP2Ye14ugArQcKs+kGPCq2l7BBcykSoIB2JStb0nU7skOYPpm4rORDQlr4fziG4d1QmmKJeqcBhf+M7C6mtZY2Tk6FQ9koemg6xOQWZos74otGwoca82BoaFZ9/pvPKZYKbtSOxAE8rVEyg50x06fKshFNvA9uYQuSQgAb194iQ98WaycxNox2H8/MepYIVD3SNYTJh6GDZ540+hA=
