dist: trusty
sudo: required
language: bash
before_install:
  - curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh | bash
notifications:
        slack:
                rooms:
                        secure:
OsTKGeEbAKGuMJ7Qdm5Rts/CBuaMTZUv9+/J0siPiHfumlw78Uv1N6Cb1Hl8rMg9O28HgyTOx0MySmKSMkH+2gdupGoGdJvby0Ag+9QcIVHPCvWvpo0Q8Pj+kqhGoTcZNSlm4yzKk+SkvmgWPH9WCyC12HPkucQOCPmd3iFbUOj6knZfaFQ2kBR1TJmDaDy0+ZZse+r+1uZsbQ2agLnYcQ/Ln/G0XnGEDHRd58EY+X43FFLg7RsqC4DzYiyk+dSsVm/O+eUsrdEOd6m/8yEJtwUlgj5qh5YKiztUc8RCrtGlbo1ssITLuLyiageYxgtMJgsf7f0+bDEvGgSXpc/3zKqZ/zLjGhga4k6HgOzLCCHGP/Y5w1nlWIQwIIXphDS11RFQJUhS9zeS6XcwuiQOoVRxzhOHCCqRAkzA/j6WbYcdiXdYwiHlVnQ+MSYdNkFh6c3BqcWMWEpqye9OYYL3wkYc+gYi68lKE/lCxe4s0RxoCaryYcwqJjjOV5r04MozbqN1xnFOGg8ouSbCV/ZlossQ4+xP810Y+YqIjtbBnOr+KUfOU0XKOrlVMyUB1lWlva9CRhHQSOTh6gISsRewqKExa1p5759SQ6/bIaezOyCrSpH6tkpf7bCbOsrxYMremzv6qkS0PwzteEhIXCMjpgP8N4/OsPEQ5JFFry3d79Y=
