---
- name: Configure APP host
  hosts: app
  become: true
  vars:
   db_host: 10.132.0.58
  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/Ganhart/db_config
        owner: Ganhart
        group: Ganhart

    - name: enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    systemd: name=puma state=restarted
