---
- name: Deploy app
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/Ganhart/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      become: true
      bundler:
        state: present
        chdir: /home/Ganhart/reddit
      tags: deploy-tag

  handlers:
  - name: reload puma
    become: true
    systemd: name=puma state=restarted
